zuul:
   routes:
      producer:
         url: http://localhost:8080
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
      hostname: DESKTOP-C641NAO
      appname: zuul
server:
   port: 8079
