server:
   #port: @serv.port@
   servlet:
      #context-path: /api
spring:
   redis:
      host: 172.16.0.42
      port: 6379
      database: 0
   jpa:
      show-sql: true
      generate-ddl: true
   profiles:
      active: default
      #active: prod
   mvc:
      view:
         prefix: /WEB-INF/
         #suffix: .jsp
   devtools:
      livereload:
         enabled: true
      restart:
         exclude: doc/**,lib/**
         additional-exclude: build/**
         log-condition-evaluation-delta: true
         enabled: true
