server:
   port: @serv.port@
   servlet:
      #context-path: /api
spring:
   profiles:
      active: default
      #active: prod
   mvc:
      view:
         prefix: /WEB-INF/
         #suffix: .jsp
   devtools:
      livereload:
         enabled: true
      restart:
         exclude: doc/**,lib/**
         additional-exclude: build/**
         log-condition-evaluation-delta: true
         enabled: true
