eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true 
      #serviceUrl: 
         #defaultZone: http://127.0.0.1:8762/eureka
   instance:
      hostname: DESKTOP-C641NAO
      appname: bookshelf
      #instanceId: :

server:
   # mvn test -Dserver.port=8080
   #port: @server.port@
   port: 9000

spring:
   thymeleaf:
      cache: false
   mustache:
      cache: false
   groovy:
      template:
         cache: false
   devtools:
      livereload:
         enabled: true
      restart:
         exclude: doc/**,lib/**
         additional-paths: script/
         additional-exclude: build/**
         log-condition-evaluation-delta: true
         enabled: true
         #trigger-file: restart-trigger.txt
