server:
   port: 8761

eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
      #serviceUrl:
         #defaultZone: http://127.0.0.1:8090/eureka
   instance:
      hostname: DESKTOP-C641NAO
      prefer-ip-address: true
      #ip-address: 127.0.0.1

spring:
   application:
      name: eureka-serv
