eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true 
      #serviceUrl: 
         #defaultZone: http://127.0.0.1:8762/eureka
   instance:
      hostname: DESKTOP-C641NAO
      appname: producer
      #instanceId: :

server:
   port: @server.port@
